build-unit-test-docker:logging: move to ibm-openbmc
There have been significant changes to upstream phosphor-logging that
our forks are not ready to handle yet. Stick with an older version of
phosphor-logging in our ibm-openbmc repo.

https://github.com/ibm-openbmc/bmcweb/pull/1435 was failing with
compilation errors in `phosphor-logging`:

```
error: 'object_path' is not a member of 'sdbusplus'; did you mean 'sdbusplus::message::object_path'?
```

This error is around the `object_path`: `sdbusplus::object_path` vs
`sdbusplus::message::object_path`.

This upstream commit caused it:
https://gerrit.openbmc.org/c/openbmc/phosphor-logging/+/89078

Signed-off-by: Gunnar Mills <gmills@us.ibm.com>